"""add_pigeon_fields_and_starting_price

Revision ID: 8309d5c65939
Revises: 57795221e86a
Create Date: 2026-03-31 17:12:29.598963
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8309d5c65939'
down_revision: Union[str, None] = '57795221e86a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
